plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\DMUNGUIA\\OneDrive - Universidad Nacional de Costa Rica\\Escritorio\\2026 I Ciclo\\ProgramacionIV\\Frontend\\labcibe-home-main\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]